export const data = [
    {
      "WKT": "POINT (-8.62324 41.1494148)",
      "title": "Galeria Fernando Santos",
      "slug": "galeria-fernando-santos",
      "mainImage": "",
      "description": "Arte Contemporânea",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua de Miguel Bombarda"
    },
    {
      "WKT": "POINT (-8.623712000000001 41.149303)",
      "title": "Galeria Presença",
      "slug": "galeria-presenca",
      "mainImage": "",
      "description": "Arte Contemporânea",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua Miguel Bombarda"
    },
    {
      "WKT": "POINT (-8.6226539 41.14806420000001)",
      "title": "Espacio Jhannia Castro",
      "slug": "espacio-jhannia-castro",
      "mainImage": "",
      "description": "Fotografia",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua de Adolfo Casais Monteiro"
    },
    {
      "WKT": "POINT (-8.620997999999998 41.1499143)",
      "title": "Galeria Adorna",
      "slug": "galeria-adorna",
      "mainImage": "",
      "description": "fotografia",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua do Rosário 193"
    },
    {
      "WKT": "POINT (-8.623479699999999 41.14924949999999)",
      "title": "Galeria Quadrado Azul",
      "slug": "galeria-quadrado-azul",
      "mainImage": "",
      "description": "Arte Contemporânea",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua Miguel Bombarda"
    },
    {
      "WKT": "POINT (-8.624305699999999 41.1492283)",
      "title": "Galeria São Mamede",
      "slug": "galeria-sao-mamede",
      "mainImage": "",
      "description": "Arte Contemporânea",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua Miguel Bombarda"
    },
    {
      "WKT": "POINT (-8.618629300000002 41.14990019999999)",
      "title": "Galeria Trindade",
      "slug": "galeria-trindade",
      "mainImage": "",
      "description": "Pintura",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua de Miguel Bombarda 141"
    },
    {
      "WKT": "POINT (-8.6217307 41.14958569999999)",
      "title": "Galeria João Lagoa",
      "slug": "galeria-joao-lagoa",
      "mainImage": "",
      "description": "Arte Contemporânea",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua de Miguel Bombarda"
    },
    {
      "WKT": "POINT (-8.6223073 41.14949739999999)",
      "title": "Cruzes Canhoto",
      "slug": "cruzes-canhoto",
      "mainImage": "",
      "description": "Arte Bruta",
      "category": "Primitiva",
      "body": "",
      "tags": [],
      "address": "Popular"
    },
    {
      "WKT": "POINT (-8.6176484 41.1500421)",
      "title": "Ó! Galería",
      "slug": "o-galeria",
      "mainImage": "",
      "description": "Ilustração",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua de Miguel Bombarda"
    },
    {
      "WKT": "POINT (-8.6234977 41.1493955)",
      "title": "Galeria Serpente",
      "slug": "galeria-serpente",
      "mainImage": "",
      "description": "Arte Contemporânea",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua Miguel Bombarda 558"
    },
    {
      "WKT": "POINT (-8.6203194 41.1495562)",
      "title": "Clink Galeria",
      "slug": "clink-galeria",
      "mainImage": "",
      "description": "Galeria de Arte e de Design Portugues",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua de Miguel Bombarda"
    },
    {
      "WKT": "POINT (-8.623210899999998 41.14926839999999)",
      "title": "Espaço Quadrasoltas",
      "slug": "espaco-quadrasoltas",
      "mainImage": "",
      "description": "Arte Contemporânea",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua Miguel Bombarda"
    },
    {
      "WKT": "POINT (-8.618974399999997 41.1498447)",
      "title": "TILSITT GALLERY",
      "slug": "tilsitt-gallery",
      "mainImage": "",
      "description": "Arte Contemporânea",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua de Miguel Bombarda"
    },
    {
      "WKT": "POINT (-8.6225676 41.1509457)",
      "title": "Galeria K11 Paiol Azul",
      "slug": "galeria-k11-paiol-azul",
      "mainImage": "",
      "description": "Arte Contemporânea",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua da Maternidade"
    },
    {
      "WKT": "POINT (-8.619601499999998 41.14978049999999)",
      "title": "Galeria Ap'arte",
      "slug": "galeria-aparte",
      "mainImage": "",
      "description": "Arte Contemporânea",
      "category": "art",
      "body": "",
      "tags": [],
      "address": "Rua de Miguel Bombarda"
    },
    {
      "WKT": "POINT (-8.622309099999999 41.14940339999999)",
      "title": "Galeria Símbolo",
      "slug": "galeria-simbolo",
      "mainImage": "",
      "description": "Arte Contemporânea",
      "category": "art",
      "body": "",
      "tags": [],
      "address": ""
    },
]
  
//     {
//       "WKT": "POINT (-8.623733999999997 41.14930389999999)",
//       "title": "Espaço REM",
//       "description": "Arte Contemporânea",
//       "category": "art",
//       "address": "Rua de Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.6183735 41.1500275)",
//       "title": "Days Are",
//       "description": "Sala de exposições",
//       "category": "art",
//       "address": "Rua de Miguel Bombarda 124",
//     },
//     {
//       "WKT": "POINT (-8.621542500000002 41.1473149)",
//       "title": "Peculiar Gallery - Galeria de arte",
//       "description": "Espaço expositivo",
//       "category": "art",
//       "address": "R. de Dom Manuel II 81/101 Loja 43 Piso-1",
//     },
//     {
//       "WKT": "POINT (-8.6227042 41.1515016)",
//       "title": "Palacete Pinto Leite",
//       "description": "Centro Cultural",
//       "category": "art",
//       "address": "Rua da Maternidade",
//     },
//     {
//       "WKT": "POINT (-8.6268467 41.1482423)",
//       "title": "Galeria Municipal do Porto",
//       "description": "Arte Contemporânea - Galeria Municipal",
//       "category": "art",
//       "address": "Jardins do Palácio de Cristal",
//     },
//     {
//       "WKT": "POINT (-8.621638299999997 41.14771269999999)",
//       "title": "Museu Nacional de Soares dos Reis",
//       "description": "Museu",
//       "category": "art",
//       "address": "R. de Dom Manuel II 44",
//     },
//     {
//       "WKT": "POINT (-8.620301999999999 41.14979460000001)",
//       "title": "Oficina",
//       "category": "Restaurante",
//       "description": "Chef Marco Gomes",
//       "address": "Rua de Miguel Bombarda 282",
//     },
//     {
//       "WKT": "POINT (-8.6204422 41.14789009999999)",
//       "title": "Época",
//       "category": "foodDrink",
//       "description": "Breakfast",
//       "Morada": "brunch",
//     },
//     {
//       "WKT": "POINT (-8.6203527 41.1509533)",
//       "title": "Apuro - Vegan Bar",
//       "category": "foodDrink",
//       "description": "Restaurante Vegan",
//       "Morada": "Rua do Breiner",
//     },
//     {
//       "WKT": "POINT (-8.623088399999999 41.1499432)",
//       "title": "Frida",
//       "category": "foodDrink",
//       "description": "Restaurante Mexicano",
//       "Morada": "R. de Adolfo Casais Monteiro",
//     },
//     {
//       "WKT": "POINT (-8.623565399999999 41.1480992)",
//       "title": "KUG",
//       "category": "foodDrink",
//       "description": "KITCHEN & URBAN GARDEN",
//       "Morada": "",
//     },
//     {
//       "WKT": "",
//       "title": "R. de Dom Manuel II",
//       "category": 178,
//       "description": "NÃO",
//       "Morada": "SIM",
//     },
//     {
//       "WKT": "POINT (-8.620190599999997 41.1489181)",
//       "title": "Sabores & Açores",
//       "category": "foodDrink",
//       "description": "Restaurante Açoreano & Indiano",
//       "Morada": "Rua de Miguel Bombarda 235",
//     },
//     {
//       "WKT": "POINT (-8.617440600000002 41.15016059999999)",
//       "title": "Mão Travessa",
//       "category": "foodDrink",
//       "description": "Restaurante",
//       "Morada": "Rua de Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.6240454 41.1493149)",
//       "title": "Bugo Art Burgers",
//       "category": "foodDrink",
//       "description": "Hamburgueria",
//       "Morada": "Rua de Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.620740600000001 41.1494125)",
//       "title": "Curral dos Petiscos",
//       "category": "foodDrink",
//       "description": "Petiscos Regionais",
//       "Morada": "Rua do Rosário Nº122",
//     },
//     {
//       "WKT": "POINT (-8.620461100000002 41.1509258)",
//       "title": "Casa Ferreira",
//       "category": "Restaurante",
//       "description": "Comida Tradicional Portuguesa",
//       "Morada": "Rua do Breiner 248",
//     },
//     {
//       "WKT": "POINT (-8.622819199999999 41.1492167)",
//       "title": "OKRA",
//       "category": "foodDrink",
//       "description": "Pizzaria",
//       "Morada": "R. de Adolfo Casais Monteiro 96",
//     },
//     {
//       "WKT": "POINT (-8.6173426 41.150172)",
//       "title": "Sabores do Sebouh",
//       "category": "foodDrink",
//       "description": "Restaurante Sírio",
//       "Morada": "Rua de Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.6203306 41.1496048)",
//       "title": "Flor de Tapioca",
//       "category": "foodDrink",
//       "description": "Tapioca Brasileira",
//       "Morada": "Rua de Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.623120100000001 41.15016790000001)",
//       "title": "Cantarinha",
//       "category": "foodDrink",
//       "description": "Francesinhas",
//       "Morada": "Largo da Maternidade de Júlio Dinis 75",
//     },
//     {
//       "WKT": "POINT (-8.6264647 41.1488766)",
//       "title": "Entre Mesas",
//       "category": "foodDrink e Cafetarias",
//       "description": "Almoços, brunch e cafetaria",
//       "Morada": "",
//     },
//     {
//       "WKT": "POINT (-8.623906900000001 41.14918369999999)",
//       "title": "Xau Laura",
//       "category": "foodDrink",
//       "description": "Comida portuguesa",
//       "Morada": "",
//     },
//     {
//       "WKT": "",
//       "title": "Rua de Miguel Bombarda 589",
//       "category": "NÃO",
//       "description": "NÃO",
//       "Morada": "Rua de Miguel Bombarda 589",
//     },
//     {
//       "WKT": "POINT (-8.621135599999999 41.1513154)",
//       "title": "Zé de Braga",
//       "category": "foodDrink",
//       "description": "Tradicional Português",
//       "Morada": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.6207512 41.1495141)",
//       "title": "Emotivo",
//       "category": "foodDrink",
//       "description": "Gastronomia Portuguesa",
//       "Morada": "Rua do Rosário",
//     },
//     {
//       "WKT": "",
//       "title": "SIM",
//       "category": "NÃO",
//       "description": "www.emotivo.pt",
//       "Morada": "",
//     },
//     {
//       "WKT": "POINT (-8.620552499999999 41.1477114)",
//       "title": "A Padoca",
//       "category": "foodDrink",
//       "description": "Padaria e Almoços",
//       "Morada": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.6227742 41.1480433)",
//       "title": "Boulevard Burger House",
//       "category": "foodDrink e Cafetarias",
//       "description": "Hamburgueria",
//       "Morada": "R. de Adolfo Casais Monteiro 17",
//     },
//     {
//       "WKT": "POINT (-8.6205453 41.1483583)",
//       "title": "Indian Italian Restaurant",
//       "category": "foodDrink",
//       "description": "Restaurante Italiano e Indiano",
//       "Morada": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.621032399999997 41.15009029999999)",
//       "title": "Amazonas",
//       "category": "Restaurante",
//       "description": "Snack Bar Restaurante",
//       "Morada": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.624854 41.14857809999999)",
//       "title": "Sabores da Amazónia",
//       "category": "foodDrink e Cafetarias",
//       "description": "restaurante brasileiro",
//       "Morada": "R. de Dom Manuel II 270",
//     },
//     {
//       "WKT": "POINT (-8.621301 41.15142000000001)",
//       "title": "Churrasqueira Domingos",
//       "category": "Churrasqueira",
//       "description": "foodDrink e Cafetarias",
//       "Morada": "Rua do Rosário 329",
//     },
   
//     {
//       "WKT": "POINT (-8.6244 41.1483962)",
//       "title": "Churrasqueira Palácio",
//       "category": "foodDrink e Cafetarias",
//       "description": "Churrasqueira",
//       "Morada": "R. de Dom Manuel II 238",
//     },
//     {
//       "WKT": "",
//       "title": "SIM",
//       "category": "NÃO",
//       "description": "churrasqueirapalacio.eatbu.com",
//       "Morada": "",
//     },
//     {
//       "WKT": "POINT (-8.620885099999999 41.1475409)",
//       "title": "Assador Típico",
//       "category": "foodDrink e Cafetarias",
//       "description": "Churrasqueira",
//       "Morada": "R. de Dom Manuel II 18",
//     },
//         {
//       "WKT": "POINT (-8.621542500000002 41.1473149)",
//       "title": "Tropical Burguer",
//       "category": "foodDrink e Cafetarias",
//       "description": "Hamburgueria e Pizarria",
//       "Morada": "R. de Dom Manuel II 8",
//     },
//     {
//       "WKT": "POINT (-8.622159700000003 41.14722159999999)",
//       "title": "Shurmann e Fernandes - Salão de Chá",
//       "category": "foodDrink e Cafetarias",
//       "description": "Restaurante e Cafetaria",
//       "Morada": "R. de Dom Manuel II 101",
//     },
//     {
//       "WKT": "POINT (-8.622159700000003 41.14722159999999)",
//       "title": "Refúgio Cervejaria",
//       "category": "foodDrink e Cafetarias",
//       "description": "Cervejaria",
//       "Morada": "R. de Dom Manuel II 10",
//     },
//     {
//       "WKT": "POINT (-8.623009699999999 41.1493058)",
//       "title": "Combi",
//       "category": "Cafetarias",
//       "description": "Cafetaria de especialidade",
//       "Morada": "Rua de Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.6208083 41.1497694)",
//       "title": "Café Célia",
//       "category": "Cafetarias",
//       "description": "Café Snack Bar",
//       "Morada": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.621129999999999 41.150415)",
//       "title": "ROSA ET AL Townhouse",
//       "category": "Cafetaria",
//       "description": "Brunch",
//       "Morada": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.621923299999999 41.1495453)",
//       "title": "The Orthodox",
//       "category": "foodDrink e Cafetarias",
//       "description": "cafetaria de especialidade",
//       "Morada": "restaurante",
//     },
//     {
//       "WKT": "POINT (-8.6224029 41.1493681)",
//       "title": "Rota do Chá",
//       "category": "Cafetaria",
//       "description": "Almoços e chá",
//       "Morada": "Rua de Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.6172299 41.1502349)",
//       "title": "Monarca",
//       "category": "Cafetarias",
//       "description": "bar e cocktails",
//       "Morada": "Rua de Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.618163899999999 41.15137389999999)",
//       "title": "Café Dunas",
//       "category": "foodDrink e Cafetarias",
//       "description": "Cafetaria",
//       "Morada": "Rua do Breiner 49",
//     },
    
//     {
//       "WKT": "POINT (-8.6224802 41.1493611)",
//       "title": "Open Box",
//       "category": "Cafetarias",
//       "description": "OpnBx - Associação Cultural e Artística",
//       "Morada": "Rua de Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.621263499999998 41.1510543)",
//       "title": "Café Encontro",
//       "category": "foodDrink e Cafetarias",
//       "description": "Cafetaria e SnackBar",
//       "Morada": "Rua do Rosário 291",
//     },
   
//     {
//       "WKT": "POINT (-8.621726899999999 41.1469899)",
//       "title": "Dente-de-Leão | Boutique-de-chá",
//       "category": "foodDrink e Cafetarias",
//       "description": "Cafetaria",
//       "Morada": "Rua D. Manuel II 81 Loja 45 Piso -1",
//     },
//     {
//       "WKT": "POINT (-8.6202965 41.1495823)",
//       "title": "CC Bombarda",
//       "category": "shop",
//       "description": "Galeria Comercial com 20 shop",
//       "address": "Rua Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.6203306 41.1496048)",
//       "title": "COLLECTIVA",
//       "category": "shop",
//       "description": "Loja de joalharia contemporânea",
//       "address": "CCBombarda",
//     },
//     {
//       "WKT": "POINT (-8.6203306 41.1496048)",
//       "title": "Cork Matters",
//       "category": "shop",
//       "description": "Loja de design",
//       "address": "cortiça",
//     },
//     {
//       "WKT": "POINT (-8.620413800000001 41.1495666)",
//       "title": "Organii",
//       "category": "shop",
//       "description": "Loja de cosmética natural",
//       "address": "CCBombarda",
//     },
//     {
//       "WKT": "POINT (-8.620234 41.1489181)",
//       "title": "Tincal lab",
//       "category": "shop",
//       "description": "Loja + atelier de joalharia contemporânea",
//       "address": "CCBombarda",
//     },
//     {
//       "WKT": "POINT (-8.6203306 41.1496048)",
//       "title": "Jewellery Experience",
//       "category": "shop",
//       "description": "Ourivesaria | Atelier de Joalharia",
//       "address": "Rua de Miguel Bombarda 285 loja 09",
//     },
//     {
//       "WKT": "POINT (-8.6202717 41.1495628)",
//       "title": "Music and Riots",
//       "category": "shop",
//       "description": "Loja de discos e publicações de música",
//       "address": "CCBombarda",
//     },
//     {
//       "WKT": "POINT (-8.6203306 41.1496048)",
//       "title": "Cave Bombarda - Natural Wine shop",
//       "category": "shop",
//       "description": "Garrafeira Vinhos Naturais",
//       "address": "Centro Comercial Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.6203306 41.1496048)",
//       "title": "Free Bird",
//       "category": "shop",
//       "description": "Loja de vestuário e acessórios",
//       "address": "CCBombarda",
//     },
//     {
//       "WKT": "POINT (-8.6203306 41.1496048)",
//       "title": "UFALUFA",
//       "category": "shop",
//       "description": "Loja para Crianças / Kids Concept Store ",
//       "address": "CCBombarda",
//     },
//     {
//       "WKT": "POINT (-8.6203306 41.1496048)",
//       "title": "Daily Day",
//       "category": "shop",
//       "description": "Loja de vestuário",
//       "address": "CCBombarda",
//     },
//     {
//       "WKT": "POINT (-8.6203278 41.1495775)",
//       "title": "Violetas Creative Studio",
//       "category": "shop",
//       "description": "Florista",
//       "address": "Rua Migue Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.6203806 41.1495182)",
//       "title": "O Berdinho",
//       "category": "shop",
//       "description": "Mercado de Biológicos Semanal",
//       "address": "Rua Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.621061399999999 41.15015999999999)",
//       "title": "CRU Loja",
//       "category": "shop",
//       "description": "Loja de design e vestuário",
//       "address": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.6230518 41.1498234)",
//       "title": "Banema Studio",
//       "category": "shop",
//       "description": "Loja de design e artigos para casa + atelier",
//       "address": "Rua Adolfo Casais Monteiro",
//     },
//     {
//       "WKT": "POINT (-8.6192748 41.14989199999999)",
//       "title": "Sir Tile Design",
//       "category": "shop",
//       "description": "Loja de meias",
//       "address": "Rua de Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.6209951 41.1499145)",
//       "title": "PATCH",
//       "category": "shop",
//       "description": "Loja de artigos vintage - vestuário e casa",
//       "address": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.6215589 41.1515837)",
//       "title": "Ziggy The Pop",
//       "category": "shop",
//       "description": "Loja de vestuário em segunda mão",
//       "address": "Rua da Maternidade",
//     },
//     {
//       "WKT": "POINT (-8.6211371 41.15062549999999)",
//       "title": "SCAR-ID",
//       "category": "shop",
//       "description": "Loja de design e moda",
//       "address": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.6196813 41.1498547)",
//       "title": "Matéria Prima",
//       "category": "shop",
//       "description": "Loja de música",
//       "address": "discos de vinil e livraria",
//     },
//     {
//       "WKT": "POINT (-8.6193671 41.149789)",
//       "title": "LOJA",
//       "category": "shop",
//       "description": "Loja de mobiliário e artigos para a casa",
//       "address": "Rua Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.6211134 41.1504655)",
//       "title": "EARLYMADE",
//       "category": "shop",
//       "description": "Loja de vestuário",
//       "address": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.6208259 41.1490389)",
//       "title": "Rosa Malva",
//       "category": "shop",
//       "description": "Loja de cerâmica + atelier",
//       "address": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.6211795 41.1514776)",
//       "title": "Otília Flowers",
//       "category": "shop",
//       "description": "Loja + Florista",
//       "address": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.621059599999999 41.1508902)",
//       "title": "Cleome",
//       "category": "shop",
//       "description": "Loja de fatos de banho e artigos de verão",
//       "address": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.6213288 41.1515928)",
//       "title": "Kuri Kuri",
//       "category": "shop",
//       "description": "Loja de produtos japoneses",
//       "address": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.623009699999999 41.1493058)",
//       "title": "Agrafo Studio",
//       "category": "shop",
//       "description": "Loja + Florista",
//       "address": "Rua Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.623104899999998 41.1492927)",
//       "title": "Papa-Livros",
//       "category": "shop",
//       "description": "Livraria para crianças",
//       "address": "Rua de Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.620832799999999 41.1491584)",
//       "title": "Liliana Guerreiro",
//       "category": "shop",
//       "description": "Loja de joalharia contemporânea",
//       "address": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.6228357 41.1494479)",
//       "title": "Bombarda 498",
//       "category": "shop",
//       "description": "Loja de vestuário e acessórios",
//       "address": "Rua Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.62644 41.1489207)",
//       "title": "Stay Wise",
//       "category": "shop",
//       "description": "Livraria e Revistas de Especialidade",
//       "address": "R. de Dom Manuel II 346 A",
//     },
//     {
//       "WKT": "POINT (-8.621986200000002 41.1505999)",
//       "title": "olá Breiner",
//       "category": "shop",
//       "description": "Loja de ilustração e objectos decorativos",
//       "address": "Rua do Breiner",
//     },
//     {
//       "WKT": "POINT (-8.6225088 41.14937039999999)",
//       "title": "L de Luz",
//       "category": "shop",
//       "description": "Loja de iluminação e candeeiros",
//       "address": "Rua Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.6230007 41.14956410000001)",
//       "title": "Copo d'Uva",
//       "category": "shop",
//       "description": "Garrafeira e Mercearia Fina",
//       "address": "Rua de Adolfo Casais Monteiro",
//     },
//     {
//       "WKT": "POINT (-8.6199859 41.1497143)",
//       "title": "Boffi Porto",
//       "category": "shop",
//       "description": "Loja de design e mobiliário",
//       "address": "Rua de Miguel Bombarda 257",
//     },
//     {
//       "WKT": "POINT (-8.6212018 41.15096070000001)",
//       "title": "Colectivo Besta",
//       "category": "shop",
//       "description": "Loja de ilustração + atelier",
//       "address": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.6200367 41.1510367)",
//       "title": "Fabric",
//       "category": "shop",
//       "description": "Loja de design e mobiliário + atelier",
//       "address": "Rua do Breiner",
//     },
//     {
//       "WKT": "POINT (-8.620740500000002 41.14931560000001)",
//       "title": "Riera Alta",
//       "category": "shop",
//       "description": "Loja de artigos para costura + atelier",
//       "address": "Rua do Rosário 110",
//     },
//     {
//       "WKT": "POINT (-8.6203194 41.1495562)",
//       "title": "Manel Jardineiro",
//       "category": "shop",
//       "description": "Florista e Plantas - especialista em kokedamas",
//       "address": "Rua de Miguel Bombarda 285",
//     },
//     {
//       "WKT": "",
//       "title": "NÃO",
//       "category": "NÃO",
//       "description": "",
//       "address": "",
//     },
//     {
//       "WKT": "POINT (-8.6214014 41.15154039999999)",
//       "title": "Gato Vadio",
//       "category": "shop",
//       "description": "Associação Cultural + Livraria",
//       "address": "Rua da Maternidade",
//     },
//     {
//       "WKT": "POINT (-8.6209951 41.1499145)",
//       "title": "Piurra Furnituring",
//       "category": "shop",
//       "description": "Loja de mobiliário + atelier",
//       "address": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.6216579 41.1495941)",
//       "title": "Chiadu Terrace",
//       "category": "shop",
//       "description": "Loja de vestuário",
//       "address": "Rua Miguel Bombarda",
//     },
//     {
//       "WKT": "",
//       "title": "SIM",
//       "category": "SIM",
//       "description": "www.chiaduterrace.com",
//       "address": "",
//     },
//     {
//       "WKT": "POINT (-8.6212087 41.1509947)",
//       "title": "Good Things Porto",
//       "category": "shop",
//       "description": "Loja de decoração",
//       "address": "Rua do Rosário 281",
//     },
//     {
//       "WKT": "POINT (-8.6227872 41.1501723)",
//       "title": "Pedro Guimarães",
//       "category": "shop",
//       "description": "Loja de decoração de ineteriores + atelier",
//       "address": "Rua do Breiner",
//     },
//     {
//       "WKT": "POINT (-8.621888199999999 41.1495671)",
//       "title": "Casa Diogo",
//       "category": "shop",
//       "description": "Mercearia Fina",
//       "address": "Rua de Miguel Bombarda 416",
//     },
//     {
//       "WKT": "POINT (-8.621714500000001 41.14734480000001)",
//       "title": "KIOSKE Cristal Park",
//       "category": "shop",
//       "description": "Papelaria",
//       "address": "Tabacaria",
//     },
//     {
//       "WKT": "POINT (-8.620973099999999 41.1497702)",
//       "title": "Quintal Bioshop",
//       "category": "shop",
//       "description": "Mercearia biológica",
//       "address": "Rua do Rosário 177",
//     },
//     {
//       "WKT": "POINT (-8.618829 41.1499598)",
//       "title": "Mercearia de Miguel Bombarda",
//       "category": "shop",
//       "description": "Mercearia e Frutaria Tradicional",
//       "address": "Rua de Miguel Bombarda 158",
//     },
//     {
//       "WKT": "POINT (-8.620359200000001 41.14955760000001)",
//       "title": "O Lagar Do Mel",
//       "category": "shop",
//       "description": "Mercearia Fina",
//       "address": "CCBombarda",
//     },
//     {
//       "WKT": "POINT (-8.6206999 41.1496123)",
//       "title": "Flor D'Açafrão",
//       "category": "shop",
//       "description": "Loja indiana de especiarias e chás",
//       "address": "Rua de Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.622614600000002 41.1478821)",
//       "title": "Maria Antónia Florista",
//       "category": "shop",
//       "description": "Florista",
//       "address": "R. de Dom Manuel II 4050",
//     },
//     {
//       "WKT": "",
//       "title": "SIM",
//       "category": "SIM",
//       "description": "https://www.mariaantoniaflorista.pt/",
//       "address": "",
//     },
//     {
//       "WKT": "POINT (-8.6202965 41.1495823)",
//       "title": "Veronique Verais",
//       "category": "shop",
//       "description": "Concept Store - vestuário",
//       "address": "Rua de Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.6205224 41.1497661)",
//       "title": "Evocações",
//       "category": "shop",
//       "description": "Antiguidades e Decoração",
//       "address": "Rua de Miguel Bombarda 308",
//     },
//     {
//       "WKT": "POINT (-8.6203306 41.1496048)",
//       "title": "Mui Concept",
//       "category": "shop",
//       "description": "Loja de chás",
//       "address": "Rua de Miguel Bombarda",
//     },
//     {
//       "WKT": "POINT (-8.621726 41.14727490000001)",
//       "title": "Centro Comercial Cristal Park",
//       "category": "shop",
//       "description": "Centro Comercial",
//       "address": "R. de Dom Manuel II 101",
//     },
//     {
//       "WKT": "",
//       "title": "",
//       "category": "",
//       "description": "",
//       "address": "",
//     },
//     {
//       "WKT": "POINT (-8.6224568 41.14783949999999)",
//       "title": "Talho do Palácio",
//       "category": "shop",
//       "description": "Talho",
//       "address": "R. de Dom Manuel II 106",
//     },
//     {
//       "WKT": "POINT (-8.6218547 41.14733349999999)",
//       "title": "Intimoda",
//       "category": "shop",
//       "description": "Vestuário Intimo",
//       "address": "R. de Dom Manuel II 101",
//     },
//     {
//       "WKT": "POINT (-8.621542500000002 41.1473149)",
//       "title": "Arminda Marques - Comercio De Lingerie",
//       "category": "Lda.",
//       "description": "shop",
//       "address": "Comercio De Lingerie",
//     },
//     {
//       "WKT": "POINT (-8.622159700000003 41.14722159999999)",
//       "title": "Pimenta Rosa",
//       "category": "shop",
//       "description": "Vestuário",
//       "address": "R. de Dom Manuel II 101",
//     },
//     {
//       "WKT": "POINT (-8.621553100000002 41.1473167)",
//       "title": "Filatélica D. Luis",
//       "category": "shop",
//       "description": "Filatélica",
//       "address": "R. D. Manuel II",
//     },
//     {
//       "WKT": "POINT (-8.6237579 41.14806859999999)",
//       "title": "Império dos Patudos",
//       "category": "shop",
//       "description": "Loja canina",
//       "address": "Rua D. Manuel II n.º 81 Loja 19",
//     },
//     {
//       "WKT": "POINT (-8.620840999999999 41.1472931)",
//       "title": "Sapataria Vaniel",
//       "category": "shop",
//       "description": "Sapataria",
//       "address": "R. de Dom Manuel II 31",
//     },
//     {
//       "WKT": "POINT (-8.622246 41.1470935)",
//       "title": "Boutique Barbara",
//       "category": "shop",
//       "description": "Vestuário",
//       "address": "R. de Dom Manuel II 101",
//     },
//     {
//       "WKT": "POINT (-8.621542500000002 41.1473149)",
//       "title": "Peso Real Licores",
//       "category": "shop",
//       "description": "Produtos Regionais e chás",
//       "address": "R. de Dom Manuel II 81 46",
//     },
//     {
//       "WKT": "POINT (-8.621542500000002 41.1473149)",
//       "title": "Fashion Secret",
//       "category": "Pronto-a-vestir",
//       "description": "shop",
//       "address": "Vestuário",
//     },
//     {
//       "WKT": "POINT (-8.622159700000003 41.14722159999999)",
//       "title": "Editorial Panorama",
//       "category": "shop",
//       "description": "Livraria",
//       "address": "R. de Dom Manuel II 101",
//     },
//     {
//       "WKT": "POINT (-8.622159700000003 41.14722159999999)",
//       "title": "Vlec",
//       "category": "shop",
//       "description": "Mobiliário",
//       "address": "R. de Dom Manuel II 101",
//     },
//     {
//       "WKT": "POINT (-8.622159700000003 41.14722159999999)",
//       "title": "Gradiva",
//       "category": "shop",
//       "description": "Publicações",
//       "address": "R. de Dom Manuel II 101",
//     },
//     {
//       "WKT": "POINT (-8.622159700000003 41.14722159999999)",
//       "title": "Dr. Joias",
//       "category": "shop",
//       "description": "Ourivesaria",
//       "address": "R. de Dom Manuel II 10",
//     },
//     {
//       "WKT": "POINT (-8.622159700000003 41.14722159999999)",
//       "title": "Casa Sãozinha",
//       "category": "shop",
//       "description": "Artesanato e Decoração",
//       "address": "Rua de Dom Manuel II",
//     },
//     {
//       "WKT": "POINT (-8.622159700000003 41.14722159999999)",
//       "title": "Alfazema Porto",
//       "category": "shop",
//       "description": "Estética e Unhas",
//       "address": "R. de Dom Manuel II 101",
//     },
//     {
//       "WKT": "POINT (-8.6210724 41.1510103)",
//       "title": "Talho do Rosário",
//       "category": "shop",
//       "description": "Talho",
//       "address": "Rua do Rosário",
//     },
//     {
//       "WKT": "POINT (-8.621359 41.1515895)",
//       "title": "Mercearia do Rosário",
//       "category": "shop",
//       "description": "mercearia tradicional",
//       "address": "Rua do Rosario 519",
//     },
//     {
//       "WKT": "POINT (-8.6212026 41.1516015)",
//       "title": "Frutaria do Rosário",
//       "category": "shop",
//       "description": "Frutaria Tradicional",
//       "address": "Rua do Rosário",
//     }
//   ]