export const data = [
  {
    WKT: "POINT (-8.62324 41.1494148)",
    title: "Galeria Fernando Santos",
    slug: "galeria-fernando-santos",
    mainImage: "",
    description: "Arte Contemporânea",
    category: "art",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.623712000000001 41.149303)",
    title: "Galeria Presença",
    slug: "galeria-presenca",
    mainImage: "",
    description: "Arte Contemporânea",
    category: "art",
    body: "",
    tags: [],
    address: "Rua Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6226539 41.14806420000001)",
    title: "Espacio Jhannia Castro",
    slug: "espacio-jhannia-castro",
    mainImage: "",
    description: "Fotografia",
    category: "art",
    body: "",
    tags: [],
    address: "Rua de Adolfo Casais Monteiro",
  },
  {
    WKT: "POINT (-8.620997999999998 41.1499143)",
    title: "Galeria Adorna",
    slug: "galeria-adorna",
    mainImage: "",
    description: "fotografia",
    category: "art",
    body: "",
    tags: [],
    address: "Rua do Rosário 193",
  },
  {
    WKT: "POINT (-8.623479699999999 41.14924949999999)",
    title: "Galeria Quadrado Azul",
    slug: "galeria-quadrado-azul",
    mainImage: "",
    description: "Arte Contemporânea",
    category: "art",
    body: "",
    tags: [],
    address: "Rua Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.624305699999999 41.1492283)",
    title: "Galeria São Mamede",
    slug: "galeria-sao-mamede",
    mainImage: "",
    description: "Arte Contemporânea",
    category: "art",
    body: "",
    tags: [],
    address: "Rua Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.618629300000002 41.14990019999999)",
    title: "Galeria Trindade",
    slug: "galeria-trindade",
    mainImage: "",
    description: "Pintura",
    category: "art",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda 141",
  },
  {
    WKT: "POINT (-8.6217307 41.14958569999999)",
    title: "Galeria João Lagoa",
    slug: "galeria-joao-lagoa",
    mainImage: "",
    description: "Arte Contemporânea",
    category: "art",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6223073 41.14949739999999)",
    title: "Cruzes Canhoto",
    slug: "cruzes-canhoto",
    mainImage: "",
    description: "Arte Bruta",
    category: "Primitiva",
    body: "",
    tags: [],
    address: "Popular",
  },
  {
    WKT: "POINT (-8.6176484 41.1500421)",
    title: "Ó! Galería",
    slug: "o-galeria",
    mainImage: "",
    description: "Ilustração",
    category: "art",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6234977 41.1493955)",
    title: "Galeria Serpente",
    slug: "galeria-serpente",
    mainImage: "",
    description: "Arte Contemporânea",
    category: "art",
    body: "",
    tags: [],
    address: "Rua Miguel Bombarda 558",
  },
  {
    WKT: "POINT (-8.6203194 41.1495562)",
    title: "Clink Galeria",
    slug: "clink-galeria",
    mainImage: "",
    description: "Galeria de Arte e de Design Portugues",
    category: "art",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.623210899999998 41.14926839999999)",
    title: "Espaço Quadrasoltas",
    slug: "espaco-quadrasoltas",
    mainImage: "",
    description: "Arte Contemporânea",
    category: "art",
    body: "",
    tags: [],
    address: "Rua Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.618974399999997 41.1498447)",
    title: "TILSITT GALLERY",
    slug: "tilsitt-gallery",
    mainImage: "",
    description: "Arte Contemporânea",
    category: "art",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6225676 41.1509457)",
    title: "Galeria K11 Paiol Azul",
    slug: "galeria-k11-paiol-azul",
    mainImage: "",
    description: "Arte Contemporânea",
    category: "art",
    body: "",
    tags: [],
    address: "Rua da Maternidade",
  },
  {
    WKT: "POINT (-8.619601499999998 41.14978049999999)",
    title: "Galeria Ap'arte",
    slug: "galeria-aparte",
    mainImage: "",
    description: "Arte Contemporânea",
    category: "art",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.622309099999999 41.14940339999999)",
    title: "Galeria Símbolo",
    slug: "galeria-simbolo",
    mainImage: "",
    description: "Arte Contemporânea",
    category: "art",
    body: "",
    tags: [],
    address: "",
  },
  {
    WKT: "POINT (-8.623733999999997 41.14930389999999)",
    title: "Espaço REM",
    slug: "espaco-rem",
    mainImage: "",
    description: "Arte Contemporânea",
    category: "art",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6183735 41.1500275)",
    title: "Days Are",
    slug: "days-are",
    mainImage: "",
    description: "Sala de exposições",
    category: "art",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda 124",
  },
  {
    WKT: "POINT (-8.621542500000002 41.1473149)",
    title: "Peculiar Gallery - Galeria de arte",
    slug: "peculiar-gallery-galeria-de-arte",
    mainImage: "",
    description: "Espaço expositivo",
    category: "art",
    body: "",
    tags: [],
    address: "R. de Dom Manuel II 81/101 Loja 43 Piso-1",
  },
  {
    WKT: "POINT (-8.6227042 41.1515016)",
    title: "Palacete Pinto Leite",
    slug: "palacete-pinto-leite",
    mainImage: "",
    description: "Centro Cultural",
    category: "art",
    body: "",
    tags: [],
    address: "Rua da Maternidade",
  },
  {
    WKT: "POINT (-8.6268467 41.1482423)",
    title: "Galeria Municipal do Porto",
    slug: "galeria-municipal-do-porto",
    mainImage: "",
    description: "Arte Contemporânea - Galeria Municipal",
    category: "art",
    body: "",
    tags: [],
    address: "Jardins do Palácio de Cristal",
  },
  {
    WKT: "POINT (-8.621638299999997 41.14771269999999)",
    title: "Museu Nacional de Soares dos Reis",
    slug: "museu-nacional-de-soares-dos-reis",
    mainImage: "",
    description: "Museu",
    category: "art",
    body: "",
    tags: [],
    address: "R. de Dom Manuel II 44",
  },
  {
    WKT: "POINT (-8.620301999999999 41.14979460000001)",
    title: "Oficina",
    slug: "oficina",
    mainImage: "",
    description: "Chef Marco Gomes",
    category: "Restaurante",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda 282",
  },
  {
    WKT: "POINT (-8.6204422 41.14789009999999)",
    title: "Época",
    slug: "epoca",
    mainImage: "",
    description: "Breakfast",
    category: "foodDrink",
    body: "",
    tags: [],
    address: "brunch",
  },
  {
    WKT: "POINT (-8.6203527 41.1509533)",
    title: "Apuro - Vegan Bar",
    slug: "apuro-vegan-bar",
    mainImage: "",
    description: "Restaurante Vegan",
    category: "foodDrink",
    body: "",
    tags: [],
    address: "Rua do Breiner",
  },
  {
    WKT: "POINT (-8.623088399999999 41.1499432)",
    title: "Frida",
    slug: "frida",
    mainImage: "",
    description: "Restaurante Mexicano",
    category: "foodDrink",
    body: "",
    tags: [],
    address: "R. de Adolfo Casais Monteiro",
  },
  {
    WKT: "POINT (-8.623565399999999 41.1480992)",
    title: "KUG",
    slug: "kug",
    mainImage: "",
    description: "KITCHEN & URBAN GARDEN",
    category: "foodDrink",
    body: "",
    tags: [],
    address: "",
  },
  {
    WKT: "",
    title: "R. de Dom Manuel II",
    slug: "r-de-dom-manuel-ii",
    mainImage: "",
    description: "NÃO",
    category: "NÃO",
    body: "",
    tags: [],
    address: "SIM",
  },
  {
    WKT: "POINT (-8.620190599999997 41.1489181)",
    title: "Sabores & Açores",
    slug: "sabores-e-acores",
    mainImage: "",
    description: "Restaurante Açoreano & Indiano",
    category: "foodDrink",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda 235",
  },
  {
    WKT: "POINT (-8.617440600000002 41.15016059999999)",
    title: "Mão Travessa",
    slug: "mao-travessa",
    mainImage: "",
    description: "Restaurante",
    category: "foodDrink",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6240454 41.1493149)",
    title: "Bugo Art Burgers",
    slug: "bugo-art-burgers",
    mainImage: "",
    description: "Hamburgueria",
    category: "foodDrink",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.620740600000001 41.1494125)",
    title: "Curral dos Petiscos",
    slug: "curral-dos-petiscos",
    mainImage: "",
    description: "Petiscos Regionais",
    category: "foodDrink",
    body: "",
    tags: [],
    address: "Rua do Rosário Nº122",
  },
  {
    WKT: "POINT (-8.620461100000002 41.1509258)",
    title: "Casa Ferreira",
    slug: "casa-ferreira",
    mainImage: "",
    description: "Comida Tradicional Portuguesa",
    category: "Restaurante",
    body: "",
    tags: [],
    address: "Rua do Breiner 248",
  },
  {
    WKT: "POINT (-8.622819199999999 41.1492167)",
    title: "OKRA",
    slug: "okra",
    mainImage: "",
    description: "Pizzaria",
    category: "foodDrink",
    body: "",
    tags: [],
    address: "R. de Adolfo Casais Monteiro 96",
  },
  {
    WKT: "POINT (-8.6173426 41.150172)",
    title: "Sabores do Sebouh",
    slug: "sabores-do-sebouh",
    mainImage: "",
    description: "Restaurante Sírio",
    category: "foodDrink",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6203306 41.1496048)",
    title: "Flor de Tapioca",
    slug: "flor-de-tapioca",
    mainImage: "",
    description: "Tapioca Brasileira",
    category: "foodDrink",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.623120100000001 41.15016790000001)",
    title: "Cantarinha",
    slug: "cantarinha",
    mainImage: "",
    description: "Francesinhas",
    category: "foodDrink",
    body: "",
    tags: [],
    address: "Largo da Maternidade de Júlio Dinis 75",
  },
  {
    WKT: "POINT (-8.6264647 41.1488766)",
    title: "Entre Mesas",
    slug: "entre-mesas",
    mainImage: "",
    description: "Almoços, brunch e cafetaria",
    category: "foodDrink e Cafetarias",
    body: "",
    tags: [],
    address: "",
  },
  {
    WKT: "POINT (-8.623906900000001 41.14918369999999)",
    title: "Xau Laura",
    slug: "xau-laura",
    mainImage: "",
    description: "Comida portuguesa",
    category: "foodDrink",
    body: "",
    tags: [],
    address: "",
  },
  {
    WKT: "",
    title: "Rua de Miguel Bombarda 589",
    slug: "rua-de-miguel-bombarda-589",
    mainImage: "",
    description: "NÃO",
    category: "NÃO",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda 589",
  },
  {
    WKT: "POINT (-8.621135599999999 41.1513154)",
    title: "Zé de Braga",
    slug: "ze-de-braga",
    mainImage: "",
    description: "Tradicional Português",
    category: "foodDrink",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.6207512 41.1495141)",
    title: "Emotivo",
    slug: "emotivo",
    mainImage: "",
    category: "foodDrink",
    description: "Gastronomia Portuguesa",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "",
    title: "SIM",
    slug: "sim",
    mainImage: "",
    category: "NÃO",
    description: "www.emotivo.pt",
    body: "",
    tags: [],
    address: "",
  },
  {
    WKT: "POINT (-8.620552499999999 41.1477114)",
    title: "A Padoca",
    slug: "a-padoca",
    mainImage: "",
    category: "foodDrink",
    description: "Padaria e Almoços",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.6227742 41.1480433)",
    title: "Boulevard Burger House",
    slug: "boulevard-burger-house",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Hamburgueria",
    body: "",
    tags: [],
    address: "R. de Adolfo Casais Monteiro 17",
  },
  {
    WKT: "POINT (-8.6205453 41.1483583)",
    title: "Indian Italian Restaurant",
    slug: "indian-italian-restaurant",
    mainImage: "",
    category: "foodDrink",
    description: "Restaurante Italiano e Indiano",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.621032399999997 41.15009029999999)",
    title: "Amazonas",
    slug: "amazonas",
    mainImage: "",
    category: "Restaurante",
    description: "Snack Bar Restaurante",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.624854 41.14857809999999)",
    title: "Sabores da Amazónia",
    slug: "sabores-da-amazonia",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "restaurante brasileiro",
    body: "",
    tags: [],
    address: "R. de Dom Manuel II 270",
  },
  {
    WKT: "POINT (-8.621301 41.15142000000001)",
    title: "Churrasqueira Domingos",
    slug: "churrasqueira-domingos",
    mainImage: "",
    category: "Churrasqueira",
    description: "foodDrink e Cafetarias",
    body: "",
    tags: [],
    address: "Rua do Rosário 329",
  },
  {
    WKT: "POINT (-8.6244 41.1483962)",
    title: "Churrasqueira Palácio",
    slug: "churrasqueira-palacio",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Churrasqueira",
    body: "",
    tags: [],
    address: "R. de Dom Manuel II 238",
  },
  {
    WKT: "",
    title: "SIM",
    slug: "sim",
    mainImage: "",
    category: "NÃO",
    description: "churrasqueirapalacio.eatbu.com",
    body: "",
    tags: [],
    address: "",
  },
  {
    WKT: "POINT (-8.620885099999999 41.1475409)",
    title: "Assador Típico",
    slug: "assador-tipico",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Churrasqueira",
    body: "",
    tags: [],
    address: "R. de Dom Manuel II 18",
  },
  {
    WKT: "POINT (-8.621542500000002 41.1473149)",
    title: "Tropical Burguer",
    slug: "tropical-burguer",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Hamburgueria e Pizarria",
    body: "",
    tags: [],
    address: "R. de Dom Manuel II 8",
  },
  {
    WKT: "POINT (-8.622159700000003 41.14722159999999)",
    title: "Shurmann e Fernandes - Salão de Chá",
    slug: "shurmann-e-fernandes-salao-de-cha",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Restaurante e Cafetaria",
    body: "",
    tags: [],
    address: "R. de Dom Manuel II 101",
  },
  {
    WKT: "POINT (-8.622159700000003 41.14722159999999)",
    title: "Refúgio Cervejaria",
    slug: "refugio-cervejaria",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Cervejaria",
    body: "",
    tags: [],
    address: "R. de Dom Manuel II 10",
  },
  {
    WKT: "POINT (-8.623009699999999 41.1493058)",
    title: "Combi",
    slug: "combi",
    mainImage: "",
    category: "Cafetarias",
    description: "Cafetaria de especialidade",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6208083 41.1497694)",
    title: "Café Célia",
    slug: "cafe-celia",
    mainImage: "",
    category: "Cafetarias",
    description: "Café Snack Bar",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.621129999999999 41.150415)",
    title: "ROSA ET AL Townhouse",
    slug: "rosa-et-al-townhouse",
    mainImage: "",
    category: "Cafetaria",
    description: "Brunch",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.6207512 41.1495141)",
    title: "Emotivo",
    slug: "emotivo",
    mainImage: "",
    category: "foodDrink",
    description: "Gastronomia Portuguesa",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "",
    title: "SIM",
    slug: "sim",
    mainImage: "",
    category: "NÃO",
    description: "www.emotivo.pt",
    body: "",
    tags: [],
    address: "",
  },
  {
    WKT: "POINT (-8.620552499999999 41.1477114)",
    title: "A Padoca",
    slug: "a-padoca",
    mainImage: "",
    category: "foodDrink",
    description: "Padaria e Almoços",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.6227742 41.1480433)",
    title: "Boulevard Burger House",
    slug: "boulevard-burger-house",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Hamburgueria",
    body: "",
    tags: [],
    address: "R. de Adolfo Casais Monteiro 17",
  },
  {
    WKT: "POINT (-8.6205453 41.1483583)",
    title: "Indian Italian Restaurant",
    slug: "indian-italian-restaurant",
    mainImage: "",
    category: "foodDrink",
    description: "Restaurante Italiano e Indiano",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.621032399999997 41.15009029999999)",
    title: "Amazonas",
    slug: "amazonas",
    mainImage: "",
    category: "Restaurante",
    description: "Snack Bar Restaurante",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.624854 41.14857809999999)",
    title: "Sabores da Amazónia",
    slug: "sabores-da-amazonia",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "restaurante brasileiro",
    body: "",
    tags: [],
    address: "R. de Dom Manuel II 270",
  },
  {
    WKT: "POINT (-8.621301 41.15142000000001)",
    title: "Churrasqueira Domingos",
    slug: "churrasqueira-domingos",
    mainImage: "",
    category: "Churrasqueira",
    description: "foodDrink e Cafetarias",
    body: "",
    tags: [],
    address: "Rua do Rosário 329",
  },
  {
    WKT: "POINT (-8.6244 41.1483962)",
    title: "Churrasqueira Palácio",
    slug: "churrasqueira-palacio",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Churrasqueira",
    body: "",
    tags: [],
    address: "R. de Dom Manuel II 238",
  },
  {
    WKT: "",
    title: "SIM",
    slug: "sim",
    mainImage: "",
    category: "NÃO",
    description: "churrasqueirapalacio.eatbu.com",
    body: "",
    tags: [],
    address: "",
  },
  {
    WKT: "POINT (-8.620885099999999 41.1475409)",
    title: "Assador Típico",
    slug: "assador-tipico",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Churrasqueira",
    body: "",
    tags: [],
    address: "R. de Dom Manuel II 18",
  },
  {
    WKT: "POINT (-8.621542500000002 41.1473149)",
    title: "Tropical Burguer",
    slug: "tropical-burguer",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Hamburgueria e Pizarria",
    body: "",
    tags: [],
    address: "R. de Dom Manuel II 8",
  },
  {
    WKT: "POINT (-8.622159700000003 41.14722159999999)",
    title: "Shurmann e Fernandes - Salão de Chá",
    slug: "shurmann-e-fernandes-salao-de-cha",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Restaurante e Cafetaria",
    body: "",
    tags: [],
    address: "R. de Dom Manuel II 101",
  },
  {
    WKT: "POINT (-8.622159700000003 41.14722159999999)",
    title: "Refúgio Cervejaria",
    slug: "refugio-cervejaria",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Cervejaria",
    body: "",
    tags: [],
    address: "R. de Dom Manuel II 10",
  },
  {
    WKT: "POINT (-8.623009699999999 41.1493058)",
    title: "Combi",
    slug: "combi",
    mainImage: "",
    category: "Cafetarias",
    description: "Cafetaria de especialidade",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6208083 41.1497694)",
    title: "Café Célia",
    slug: "cafe-celia",
    mainImage: "",
    category: "Cafetarias",
    description: "Café Snack Bar",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.621129999999999 41.150415)",
    title: "ROSA ET AL Townhouse",
    slug: "rosa-et-al-townhouse",
    mainImage: "",
    category: "Cafetaria",
    description: "Brunch",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.621923299999999 41.1495453)",
    title: "The Orthodox",
    slug: "the-orthodox",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Cafetaria de especialidade",
    body: "",
    tags: [],
    address: "restaurante",
  },
  {
    WKT: "POINT (-8.6224029 41.1493681)",
    title: "Rota do Chá",
    slug: "rota-do-cha",
    mainImage: "",
    category: "Cafetaria",
    description: "Almoços e chá",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6172299 41.1502349)",
    title: "Monarca",
    slug: "monarca",
    mainImage: "",
    category: "Cafetarias",
    description: "Bar e cocktails",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.618163899999999 41.15137389999999)",
    title: "Café Dunas",
    slug: "cafe-dunas",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Cafetaria",
    body: "",
    tags: [],
    address: "Rua do Breiner 49",
  },
  {
    WKT: "POINT (-8.6224802 41.1493611)",
    title: "Open Box",
    slug: "open-box",
    mainImage: "",
    category: "Cafetarias",
    description: "OpnBx - Associação Cultural e Artística",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.621263499999998 41.1510543)",
    title: "Café Encontro",
    slug: "cafe-encontro",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Cafetaria e SnackBar",
    body: "",
    tags: [],
    address: "Rua do Rosário 291",
  },
  {
    WKT: "POINT (-8.621726899999999 41.1469899)",
    title: "Dente-de-Leão | Boutique-de-chá",
    slug: "dente-de-leao-boutique-de-cha",
    mainImage: "",
    category: "foodDrink e Cafetarias",
    description: "Cafetaria",
    body: "",
    tags: [],
    address: "Rua D. Manuel II 81 Loja 45 Piso -1",
  },
  {
    WKT: "POINT (-8.6202965 41.1495823)",
    title: "CC Bombarda",
    slug: "cc-bombarda",
    mainImage: "",
    category: "shop",
    description: "Galeria Comercial com 20 shops",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6203306 41.1496048)",
    title: "COLLECTIVA",
    slug: "collectiva",
    mainImage: "",
    category: "shop",
    description: "Loja de joalharia contemporânea",
    body: "",
    tags: [],
    address: "CCBombarda",
  },
  {
    WKT: "POINT (-8.6203306 41.1496048)",
    title: "Cork Matters",
    slug: "cork-matters",
    mainImage: "",
    category: "shop",
    description: "Loja de design",
    body: "",
    tags: [],
    address: "cortiça",
  },
  {
    WKT: "POINT (-8.620413800000001 41.1495666)",
    title: "Organii",
    slug: "organii",
    mainImage: "",
    category: "shop",
    description: "Loja de cosmética natural",
    body: "",
    tags: [],
    address: "CCBombarda",
  },
  {
    WKT: "POINT (-8.620234 41.1489181)",
    title: "Tincal lab",
    slug: "tincal-lab",
    mainImage: "",
    category: "shop",
    description: "Loja + atelier de joalharia contemporânea",
    body: "",
    tags: [],
    address: "CCBombarda",
  },
  {
    WKT: "POINT (-8.6203306 41.1496048)",
    title: "Jewellery Experience",
    slug: "jewellery-experience",
    mainImage: "",
    category: "shop",
    description: "Ourivesaria | Atelier de Joalharia",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda 285 loja 09",
  },
  {
    WKT: "POINT (-8.6202717 41.1495628)",
    title: "Music and Riots",
    slug: "music-and-riots",
    mainImage: "",
    category: "shop",
    description: "Loja de discos e publicações de música",
    body: "",
    tags: [],
    address: "CCBombarda",
  },
  {
    WKT: "POINT (-8.6203306 41.1496048)",
    title: "Cave Bombarda - Natural Wine shop",
    slug: "cave-bombarda-natural-wine-shop",
    mainImage: "",
    category: "shop",
    description: "Garrafeira Vinhos Naturais",
    body: "",
    tags: [],
    address: "Centro Comercial Bombarda",
  },
  {
    WKT: "POINT (-8.6203306 41.1496048)",
    title: "Free Bird",
    slug: "free-bird",
    mainImage: "",
    category: "shop",
    description: "Loja de vestuário e acessórios",
    body: "",
    tags: [],
    address: "CCBombarda",
  },
  {
    WKT: "POINT (-8.6203306 41.1496048)",
    title: "UFALUFA",
    slug: "ufalufa",
    mainImage: "",
    category: "shop",
    description: "Loja para Crianças / Kids Concept Store",
    body: "",
    tags: [],
    address: "CCBombarda",
  },
  {
    WKT: "POINT (-8.6203306 41.1496048)",
    title: "Daily Day",
    slug: "daily-day",
    mainImage: "",
    category: "shop",
    description: "Loja de vestuário",
    body: "",
    tags: [],
    address: "CCBombarda",
  },
  {
    WKT: "POINT (-8.6203278 41.1495775)",
    title: "Violetas Creative Studio",
    slug: "violetas-creative-studio",
    category: "shop",
    description: "Florista",
    body: "",
    tags: [],
    address: "Rua Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6203806 41.1495182)",
    title: "O Berdinho",
    slug: "o-berdinho",
    category: "shop",
    description: "Mercado de Biológicos Semanal",
    body: "",
    tags: [],
    address: "Rua Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.621061399999999 41.15015999999999)",
    title: "CRU Loja",
    slug: "cru-loja",
    category: "shop",
    description: "Loja de design e vestuário",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.6230518 41.1498234)",
    title: "Banema Studio",
    slug: "banema-studio",
    category: "shop",
    description: "Loja de design e artigos para casa + atelier",
    body: "",
    tags: [],
    address: "Rua Adolfo Casais Monteiro",
  },
  {
    WKT: "POINT (-8.6192748 41.14989199999999)",
    title: "Sir Tile Design",
    slug: "sir-tile-design",
    category: "shop",
    description: "Loja de meias",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6209951 41.1499145)",
    title: "PATCH",
    slug: "patch",
    category: "shop",
    description: "Loja de artigos vintage - vestuário e casa",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.6215589 41.1515837)",
    title: "Ziggy The Pop",
    slug: "ziggy-the-pop",
    category: "shop",
    description: "Loja de vestuário em segunda mão",
    body: "",
    tags: [],
    address: "Rua da Maternidade",
  },
  {
    WKT: "POINT (-8.6211371 41.15062549999999)",
    title: "SCAR-ID",
    slug: "scar-id",
    category: "shop",
    description: "Loja de design e moda",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.6196813 41.1498547)",
    title: "Matéria Prima",
    slug: "materia-prima",
    category: "shop",
    description: "Loja de música",
    body: "",
    tags: [],
    address: "discos de vinil e livraria",
  },
  {
    WKT: "POINT (-8.6193671 41.149789)",
    title: "LOJA",
    slug: "loja",
    category: "shop",
    description: "Loja de mobiliário e artigos para a casa",
    body: "",
    tags: [],
    address: "Rua Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6211134 41.1504655)",
    title: "EARLYMADE",
    slug: "earlymade",
    category: "shop",
    description: "Loja de vestuário",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.6208259 41.1490389)",
    title: "Rosa Malva",
    slug: "rosa-malva",
    category: "shop",
    description: "Loja de cerâmica + atelier",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.6211795 41.1514776)",
    title: "Otília Flowers",
    slug: "otilia-flowers",
    category: "shop",
    description: "Loja + Florista",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.621059599999999 41.1508902)",
    title: "Cleome",
    slug: "cleome",
    category: "shop",
    description: "Loja de fatos de banho e artigos de verão",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.6213288 41.1515928)",
    title: "Kuri Kuri",
    slug: "kuri-kuri",
    category: "shop",
    description: "Loja de produtos japoneses",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.623009699999999 41.1493058)",
    title: "Agrafo Studio",
    slug: "agrafo-studio",
    category: "shop",
    description: "Loja + Florista",
    body: "",
    tags: [],
    address: "Rua Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.623104899999998 41.1492927)",
    title: "Papa-Livros",
    slug: "papa-livros",
    category: "shop",
    description: "Livraria para crianças",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.620832799999999 41.1491584)",
    title: "Liliana Guerreiro",
    slug: "liliana-guerreiro",
    category: "shop",
    description: "Loja de joalharia contemporânea",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.6228357 41.1494479)",
    title: "Bombarda 498",
    slug: "bombarda-498",
    category: "shop",
    description: "Loja de vestuário e acessórios",
    body: "",
    tags: [],
    address: "Rua de Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6203278 41.1495775)",
    title: "Violetas Creative Studio",
    slug: "violetas-creative-studio",
    category: "shop",
    description: "Florista",
    mainImage: "/path/to/image.jpg",
    body: "",
    tags: [],
    address: "Rua Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.6203806 41.1495182)",
    title: "O Berdinho",
    slug: "o-berdinho",
    category: "shop",
    description: "Mercado de Biológicos Semanal",
    mainImage: "/path/to/image.jpg",
    body: "",
    tags: [],
    address: "Rua Miguel Bombarda",
  },
  {
    WKT: "POINT (-8.621061399999999 41.15015999999999)",
    title: "CRU Loja",
    slug: "cru-loja",
    category: "shop",
    description: "Loja de design e vestuário",
    mainImage: "/path/to/image.jpg",
    body: "",
    tags: [],
    address: "Rua do Rosário",
  },
  {
    WKT: "POINT (-8.6212018 41.15096070000001)",
    title: "Colectivo Besta",
    slug: "colectivo-besta",
    category: "shop",
    description: "Loja de ilustração + atelier",
    address: "Rua do Rosário",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6200367 41.1510367)",
    title: "Fabric",
    slug: "fabric",
    category: "shop",
    description: "Loja de design e mobiliário + atelier",
    address: "Rua do Breiner",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.620740500000002 41.14931560000001)",
    title: "Riera Alta",
    slug: "riera-alta",
    category: "shop",
    description: "Loja de artigos para costura + atelier",
    address: "Rua do Rosário 110",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6203194 41.1495562)",
    title: "Manel Jardineiro",
    slug: "manel-jardineiro",
    category: "shop",
    description: "Florista e Plantas - especialista em kokedamas",
    address: "Rua de Miguel Bombarda 285",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "",
    title: "NÃO",
    slug: "nao",
    category: "NÃO",
    description: "",
    address: "",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6214014 41.15154039999999)",
    title: "Gato Vadio",
    slug: "gato-vadio",
    category: "shop",
    description: "Associação Cultural + Livraria",
    address: "Rua da Maternidade",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.62644 41.1489207)",
    title: "Stay Wise",
    slug: "stay-wise",
    category: "shop",
    description: "Livraria e Revistas de Especialidade",
    address: "R. de Dom Manuel II 346 A",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.621986200000002 41.1505999)",
    title: "olá Breiner",
    slug: "ola-breiner",
    category: "shop",
    description: "Loja de ilustração e objectos decorativos",
    address: "Rua do Breiner",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6225088 41.14937039999999)",
    title: "L de Luz",
    slug: "l-de-luz",
    category: "shop",
    description: "Loja de iluminação e candeeiros",
    address: "Rua Miguel Bombarda",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6230007 41.14956410000001)",
    title: "Copo d'Uva",
    slug: "copo-duva",
    category: "shop",
    description: "Garrafeira e Mercearia Fina",
    address: "Rua de Adolfo Casais Monteiro",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6199859 41.1497143)",
    title: "Boffi Porto",
    slug: "boffi-porto",
    category: "shop",
    description: "Loja de design e mobiliário",
    address: "Rua de Miguel Bombarda 257",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6209951 41.1499145)",
    title: "Piurra Furnituring",
    slug: "piurra-furnituring",
    category: "shop",
    description: "Loja de mobiliário + atelier",
    address: "Rua do Rosário",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6216579 41.1495941)",
    title: "Chiadu Terrace",
    slug: "chiadu-terrace",
    category: "shop",
    description: "Loja de vestuário",
    address: "Rua Miguel Bombarda",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "",
    title: "SIM",
    slug: "sim",
    category: "SIM",
    description: "www.chiaduterrace.com",
    address: "",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6212087 41.1509947)",
    title: "Good Things Porto",
    slug: "good-things-porto",
    category: "shop",
    description: "Loja de decoração",
    address: "Rua do Rosário 281",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6227872 41.1501723)",
    title: "Pedro Guimarães",
    slug: "pedro-guimaraes",
    category: "shop",
    description: "Loja de decoração de interiores + atelier",
    address: "Rua do Breiner",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.621888199999999 41.1495671)",
    title: "Casa Diogo",
    slug: "casa-diogo",
    category: "shop",
    description: "Mercearia Fina",
    address: "Rua de Miguel Bombarda 416",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.621714500000001 41.14734480000001)",
    title: "KIOSKE Cristal Park",
    slug: "kioske-cristal-park",
    category: "shop",
    description: "Papelaria",
    address: "Tabacaria",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.620973099999999 41.1497702)",
    title: "Quintal Bioshop",
    slug: "quintal-bioshop",
    category: "shop",
    description: "Mercearia biológica",
    address: "Rua do Rosário 177",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.618829 41.1499598)",
    title: "Mercearia de Miguel Bombarda",
    slug: "mercearia-de-miguel-bombarda",
    category: "shop",
    description: "Mercearia e Frutaria Tradicional",
    address: "Rua de Miguel Bombarda 158",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.620359200000001 41.14955760000001)",
    title: "O Lagar Do Mel",
    slug: "o-lagar-do-mel",
    category: "shop",
    description: "Mercearia Fina",
    address: "CCBombarda",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6206999 41.1496123)",
    title: "Flor D'Açafrão",
    slug: "flor-dacafrão",
    category: "shop",
    description: "Loja indiana de especiarias e chás",
    address: "Rua de Miguel Bombarda",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.622614600000002 41.1478821)",
    title: "Maria Antónia Florista",
    slug: "maria-antonia-florista",
    category: "shop",
    description: "Florista",
    address: "R. de Dom Manuel II 4050",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "",
    title: "SIM",
    slug: "sim-1",
    category: "SIM",
    description: "https://www.mariaantoniaflorista.pt/",
    address: "",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6202965 41.1495823)",
    title: "Veronique Verais",
    slug: "veronique-verais",
    category: "shop",
    description: "Concept Store - vestuário",
    address: "Rua de Miguel Bombarda",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6205224 41.1497661)",
    title: "Evocações",
    slug: "evocacoes",
    category: "shop",
    description: "Antiguidades e Decoração",
    address: "Rua de Miguel Bombarda 308",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6203306 41.1496048)",
    title: "Mui Concept",
    slug: "mui-concept",
    category: "shop",
    description: "Loja de chás",
    address: "Rua de Miguel Bombarda",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.621726 41.14727490000001)",
    title: "Centro Comercial Cristal Park",
    slug: "centro-comercial-cristal-park",
    category: "shop",
    description: "Centro Comercial",
    address: "R. de Dom Manuel II 101",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "",
    title: "",
    slug: "",
    category: "",
    description: "",
    address: "",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6224568 41.14783949999999)",
    title: "Talho do Palácio",
    slug: "talho-do-palacio",
    category: "shop",
    description: "Talho",
    address: "R. de Dom Manuel II 106",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6218547 41.14733349999999)",
    title: "Intimoda",
    slug: "intimoda",
    category: "shop",
    description: "Vestuário Intimo",
    address: "R. de Dom Manuel II 101",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.621542500000002 41.1473149)",
    title: "Arminda Marques - Comercio De Lingerie",
    slug: "arminda-marques-comercio-de-lingerie",
    category: "Lda.",
    description: "shop",
    address: "Comercio De Lingerie",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.622159700000003 41.14722159999999)",
    title: "Pimenta Rosa",
    slug: "pimenta-rosa",
    category: "shop",
    description: "Vestuário",
    address: "R. de Dom Manuel II 101",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.621553100000002 41.1473167)",
    title: "Filatélica D. Luis",
    slug: "filatelica-d-luis",
    category: "shop",
    description: "Filatélica",
    address: "R. D. Manuel II",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6237579 41.14806859999999)",
    title: "Império dos Patudos",
    slug: "imperio-dos-patudos",
    category: "shop",
    description: "Loja canina",
    address: "Rua D. Manuel II n.º 81 Loja 19",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.620840999999999 41.1472931)",
    title: "Sapataria Vaniel",
    slug: "sapataria-vaniel",
    category: "shop",
    description: "Sapataria",
    address: "R. de Dom Manuel II 31",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.622246 41.1470935)",
    title: "Boutique Barbara",
    slug: "boutique-barbara",
    category: "shop",
    description: "Vestuário",
    address: "R. de Dom Manuel II 101",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.621542500000002 41.1473149)",
    title: "Peso Real Licores",
    slug: "peso-real-licores",
    category: "shop",
    description: "Produtos Regionais e chás",
    address: "R. de Dom Manuel II 81 46",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.621542500000002 41.1473149)",
    title: "Fashion Secret",
    slug: "fashion-secret",
    category: "Pronto-a-vestir",
    description: "shop",
    address: "Vestuário",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.622159700000003 41.14722159999999)",
    title: "Editorial Panorama",
    slug: "editorial-panorama",
    category: "shop",
    description: "Livraria",
    address: "R. de Dom Manuel II 101",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.622159700000003 41.14722159999999)",
    title: "Vlec",
    slug: "vlec",
    category: "shop",
    description: "Mobiliário",
    address: "R. de Dom Manuel II 101",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.622159700000003 41.14722159999999)",
    title: "Gradiva",
    slug: "gradiva",
    category: "shop",
    description: "Publicações",
    address: "R. de Dom Manuel II 101",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.622159700000003 41.14722159999999)",
    title: "Dr. Joias",
    slug: "dr-joias",
    category: "shop",
    description: "Ourivesaria",
    address: "R. de Dom Manuel II 10",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.622159700000003 41.14722159999999)",
    title: "Casa Sãozinha",
    slug: "casa-saozinha",
    category: "shop",
    description: "Artesanato e Decoração",
    address: "Rua de Dom Manuel II",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.622159700000003 41.14722159999999)",
    title: "Alfazema Porto",
    slug: "alfazema-porto",
    category: "shop",
    description: "Estética e Unhas",
    address: "R. de Dom Manuel II 101",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6210724 41.1510103)",
    title: "Talho do Rosário",
    slug: "talho-do-rosario",
    category: "shop",
    description: "Talho",
    address: "Rua do Rosário",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.621359 41.1515895)",
    title: "Mercearia do Rosário",
    slug: "mercearia-do-rosario",
    category: "shop",
    description: "mercearia tradicional",
    address: "Rua do Rosario 519",
    mainImage: "",
    tags: [],
    body: "",
  },
  {
    WKT: "POINT (-8.6212026 41.1516015)",
    title: "Frutaria do Rosário",
    slug: "frutaria-do-rosario",
    category: "shop",
    description: "Frutaria Tradicional",
    address: "Rua do Rosário",
    mainImage: "",
    tags: [],
    body: "",
  },
];
